export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const ADD_PET_START = "ADD_PET_START";
export const ADD_PET_SUCCESS = "ADD_PET_SUCCESS";
export const ADD_PET_FAILED = "ADD_PET_FAILED";

export const FETCH_PETS_START = "FETCH_PETS_START";
export const FETCH_ALL_PETS = "FETCH_ALL_PET";
export const FETCH_PETS_SUCCESS = "FETCH_PET_SUCCESS";
export const FETCH_PETS_FAILED = "FETCH_PET_FAILED";

export const CREATE_PLAYDATE_START = "CREATE_PLAYDATE";
export const CREATE_PLAYDATE_SUCCESS = "CREATE_PLAYDATE_SUCCESS";
export const CREATE_PLAYDATE_FAILED = "CREATE_PLAYDATE_FAILED";

export const FETCH_PLAYDATES_START = "FETCH_PLAYDATES_START";
export const FETCH_ALL_PLAYDATES = "FETCH_ALL_PLAYDATES";
export const FETCH_PlAYDATES_SUCCESS = "FETCH_PlAYDATES_SUCCESS";
export const FETCH_PLAYDATES_FAILED = "FETCH_PLAYDATES_FAILED";
